# Generated by Django 4.0.4 on 2022-05-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=50)),
                ('ply_number', models.IntegerField(default=0)),
                ('dwnld_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='static/images/website/singers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rgst_date', models.DateTimeField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('ply_number', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('dwnld_number', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='media/musics/<django.db.models.fields.CharField>/')),
                ('playlist', models.ManyToManyField(to='website.playlist')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.singer')),
            ],
        ),
    ]
