# Generated by Django 4.0.4 on 2022-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.FileField(upload_to='images/website/singers/'),
        ),
    ]
